/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-variant": "#d9e4ea",
          "on-primary-fixed-variant": "#4a40e0",
          "background": "#f7f9fb",
          "tertiary": "#006d4a",
          "surface-container-lowest": "#ffffff",
          "on-surface": "#2a3439",
          "error-container": "#ff8b9a",
          "on-surface-variant": "#566166",
          "surface": "#f7f9fb",
          "tertiary-fixed-dim": "#58e7ab",
          "primary-fixed-dim": "#d2d0ff",
          "outline-variant": "#a9b4b9",
          "on-primary": "#faf6ff",
          "error": "#9e3f4e",
          "secondary-container": "#d3e4fe",
          "on-secondary": "#f7f9ff",
          "on-primary-fixed": "#2a13c5",
          "tertiary-dim": "#005f40",
          "surface-container-highest": "#d9e4ea",
          "surface-bright": "#f7f9fb",
          "on-error": "#fff7f7",
          "secondary-fixed": "#d3e4fe",
          "surface-container": "#e8eff3",
          "on-tertiary-container": "#005a3c",
          "on-tertiary": "#e6ffee",
          "tertiary-fixed": "#69f6b8",
          "secondary-fixed-dim": "#c5d6f0",
          "on-primary-container": "#3f33d6",
          "tertiary-container": "#69f6b8",
          "on-secondary-fixed": "#314055",
          "inverse-surface": "#0b0f10",
          "on-background": "#2a3439",
          "primary-fixed": "#e2dfff",
          "secondary-dim": "#44546a",
          "on-secondary-container": "#435368",
          "surface-container-high": "#e1e9ee",
          "on-tertiary-fixed": "#00452d",
          "on-tertiary-fixed-variant": "#006544",
          "secondary": "#506076",
          "inverse-primary": "#8582ff",
          "primary-container": "#e2dfff",
          "on-error-container": "#782232",
          "on-secondary-fixed-variant": "#4d5d73",
          "primary-dim": "#4034d7",
          "primary": "#4d44e3",
          "surface-tint": "#4d44e3",
          "outline": "#717c82",
          "surface-dim": "#cfdce3",
          "error-dim": "#4f0116",
          "surface-container-low": "#f0f4f7",
          "inverse-on-surface": "#9a9d9f"
      },
      "borderRadius": {
          "DEFAULT": "0.125rem",
          "lg": "0.25rem",
          "xl": "0.5rem",
          "full": "0.75rem"
      },
      "fontFamily": {
          "sans": ["Inter", "sans-serif"],
          "headline": ["Inter", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"],
          "inter": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
